### ISSUE TITLE
Whitespace in grammar

### ISSUE THREAD

**Issue by bkaestner** [bkaestner/sfcl#1]
The current tests in `next` are somewhat ugly due to problems with `\n` and other whitespace. The parser doesn't actually follow the grammar, since it uses `trim`, e.g.

```haskell
-- | Parses a block that contains only lyrics.
lblockParser :: Parser Block
lblockParser = LBlock . trim <$> (skipSomeSpace *> many1 lyricsym)
  where
    lyricsym = satisfy $ notInClass "@\r\n"

-- | Helper, which trims whitespace at front and end of a string.
trim :: String -> String
trim = unwords . filter (not . null) . words
```

But the grammar uses a left-side trim:

    block   = {spaces} , (clblock | cblock | lblock)
    clblock = cblock , lblock
    cblock  = "@chord{" , chord , "}"
    lblock  = lyrics

## Todo

- [ ] Check how other languages define their grammar and parser regarding whitespace
- [ ] Fix the grammar (if necessary) to get rid of the left-side-only trim
- [ ] Fix the parser (if necessary) if the blocks should __not__ only contain trimmed values (this is the default at the moment.
- [ ] If the lyrics/chords should always be trimmed, add a test to make sure that they actually _are_ trimmed.
